ngrok_url: "https://0c2e-94-181-83-5.ngrok.io"
telegram_token: "2141495170:AAHxcBtBSR2ALwk88DRBZfah0q_Td_cFFdc"
port: "80"
telegram_url: "https://api.telegram.org/bot"

database: 
  host: "localhost"
  username: "root"
  password: "password"
  dbname: "telegramdb"
  port: "5432"
  sslmode: "false"

